import { Inter } from 'next/font/google'
import './globals.css'
import Provider from '@/components/provider'
import Nav from '@/components/Nav.js'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children,session }) {
  return (
    <html lang="en">
      <Provider>
      <body className={inter.className}>
        <div className='gradient'></div>
        <Nav></Nav>
        {children}
        </body>
        </Provider>
    </html>
  )
}
